/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStudioRouteImport } from './routes/_app.studio'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCertificatesRouteImport } from './routes/_app.certificates'
import { Route as AppBulkRouteImport } from './routes/_app.bulk'
import { Route as AppCertificatesIdRouteImport } from './routes/_app.certificates.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppBulkRoute = AppBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesIdRoute = AppCertificatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCertificatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof AppBulkRoute
  '/certificates': typeof AppCertificatesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/studio': typeof AppStudioRoute
  '/certificates/$id': typeof AppCertificatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof AppBulkRoute
  '/certificates': typeof AppCertificatesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/studio': typeof AppStudioRoute
  '/certificates/$id': typeof AppCertificatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/bulk': typeof AppBulkRoute
  '/_app/certificates': typeof AppCertificatesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/studio': typeof AppStudioRoute
  '/_app/certificates/$id': typeof AppCertificatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bulk'
    | '/certificates'
    | '/dashboard'
    | '/studio'
    | '/certificates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bulk'
    | '/certificates'
    | '/dashboard'
    | '/studio'
    | '/certificates/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/bulk'
    | '/_app/certificates'
    | '/_app/dashboard'
    | '/_app/studio'
    | '/_app/certificates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bulk': {
      id: '/_app/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof AppBulkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates/$id': {
      id: '/_app/certificates/$id'
      path: '/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof AppCertificatesIdRouteImport
      parentRoute: typeof AppCertificatesRoute
    }
  }
}

interface AppCertificatesRouteChildren {
  AppCertificatesIdRoute: typeof AppCertificatesIdRoute
}

const AppCertificatesRouteChildren: AppCertificatesRouteChildren = {
  AppCertificatesIdRoute: AppCertificatesIdRoute,
}

const AppCertificatesRouteWithChildren = AppCertificatesRoute._addFileChildren(
  AppCertificatesRouteChildren,
)

interface AppRouteChildren {
  AppBulkRoute: typeof AppBulkRoute
  AppCertificatesRoute: typeof AppCertificatesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppStudioRoute: typeof AppStudioRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBulkRoute: AppBulkRoute,
  AppCertificatesRoute: AppCertificatesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppStudioRoute: AppStudioRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
